# docker-compose.yml
version: '3.8'

services:
  db:
    image: ${POSTGRES_IMAGE:-postgres:16-alpine}
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres-atividade3-fiap}
    restart: always
    
    # Variáveis de ambiente para configuração do banco de dados
    environment:
      POSTGRES_DB: ${DB_NAME:-atividade3-fiap}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    
    # Mapeamento da porta
    ports:
      - "${DB_PORT:-5432}:5432"
      
    # Mapeamento de volumes
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./init_files/init.sql:/docker-entrypoint-initdb.d/init.sql
      

volumes:
  postgres_data: